### Verbo GET – listar
GET http://localhost:8000/funcionario/ HTTP/1.1
content-type: application/json
x-token: abcBolinhasToken
x-key: abcBolinhasKey

### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
content-type: application/json

{
    "nome" : "Regis Camargo",
    "cpf" : "18598612258",
    "telefone" : "49988234567",
    "senha" : "bolinhas",
    "matricula" : "12345",
    "grupo" : 1
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/1 HTTP/1.1
content-type: application/json

{
    "nome" : "Regis Santos Camargo",
    "cpf" : "18878112958",
    "telefone" : "49898989",
    "senha" : "abc",
    "matricula" : "54321",
    "grupo" : 2
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1
content-type: application/json