### Verbo GET – listar
GET http://localhost:8000/produto/ HTTP/1.1
content-type: application/json

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "nome" : "goiabada",
    "descricao" : "abcbolinhas@",
    "foto" : true,
    "valor_unitario" : 1.50
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/1 HTTP/1.1
content-type: application/json

{
    "nome" : "goiabada",
    "descricao" : "goiabada de maraguja",
    "foto" : 1,
    "valor_unitario" : 1.50
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/1 HTTP/1.1
content-type: application/json