### Verbo GET – listar
GET http://localhost:8000/cliente/ HTTP/1.1
content-type: application/json

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome" : "Bolinhas dos Testes",
    "cpf" : "12345678909",
    "telefone" : "49898989",
    "compra_fiado" : 1,
    "dia_fiado": 20,
    "senha": "123"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type: application/json

{
    "nome" : "Bolinhas dos Testes",
    "cpf" : "12345678909",
    "telefone" : "49898989",
    "compra_fiado" : 1,
    "dia_fiado": 30,
    "senha": "123"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type: application/json

