### Verbo GET – listar
GET http://localhost:8000/funcionario/0 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/4 HTTP/1.1
content-type: application/json

{
    "nome" : "Abc da Silva",
    "descricao" : "abcbolinhas@",
    "foto" : "...",
    "valor_unitario" : "1.50",

}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/2 HTTP/1.1
content-type: application/json

{
    "nome" : "goiabada",
    "descricao" : "goiabada de maraguja",
    "foto" : "...",
    "valor_unitario" : "1.50",
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/3 HTTP/1.1