### Verbo GET – listar
GET http://localhost:8000/cliente HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

### Verbo GET – listar todos
curl -X 'GET' \
    'http://localhost:8000/cliente/' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'

### Verbo POST - adicionar
POST http://localhost:8000/cliente/ HTTP/1.1
content-type : application/json
x-token: abcBolinhasToken
x-key: abcBolinhasKey

{
    "nome" : "Regis",
    "cpf" : "3",
    "telefone" : "3",
    "compra_fiado" : 0,
    "dia_fiado" : 2,
    "senha" : "abc"
}

### Verbo PUT - atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type : application/json
x-token: abcBolinhasToken
x-key: abcBolinhasKey

{
    "nome" : "Régis",
    "cpf" : "23213312315",
    "telefone" : "49982345567",
    "compra_fiado" : 1,
    "dia_fiado" : 20,
    "senha" : "aaa"
}

### Verbo DELETE - atualiza
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type : application/json
x-token: abcBolinhasToken
x-key: abcBolinhasKey