### Verbo GET – listar
GET http://localhost:8000/funcionario HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

### Verbo GET – listar todos
curl -X 'GET' \
    'http://localhost:8000/funcionario/' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'

### Verbo POST - adicionar
POST http://localhost:8000/funcionario/ HTTP/1.1
content-type : application/json
x-token: abcBolinhasToken
x-key: abcBolinhasKey

{
    "nome" : "regis",
    "matricula" : "2231222",
    "cpf" : "333223333",
    "telefone" : "44321444",
    "grupo" : "4",
    "senha" : "555321455"
}

### Verbo PUT - atualiza
PUT http://127.0.0.1:8000/funcionario/2 HTTP/1.1
content-type : application/json
x-token: abcBolinhasToken
x-key: abcBolinhasKey

{
    "nome" : "regis" ,
    "matricula" : "2213124" ,
    "cpf" : "32314" ,
    "telefone" : "441232" ,
    "grupo" : 5 ,
    "senha" : "62314"
}

### Verbo DELL - atualiza
DELETE  http://127.0.0.1:8000/funcionario/2 HTTP/1.1
content-type : application/json
x-token: abcBolinhasToken
x-key: abcBolinhasKey